# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import tensorflow as tf
from PyQt5 import QtCore, QtGui, QtWidgets
from elevatorui import *


if __name__ == "__main__":
    multithreading()
